# Generated by Django 3.2.9 on 2021-12-01 23:46

import charidfield.fields
import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, max_length=5, prefix='prod', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
