# Generated by Django 3.2.9 on 2021-12-01 23:55

import charidfield.fields
import cuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=charidfield.fields.CharIDField(default=cuid.cuid, max_length=30, prefix='prod_', primary_key=True, serialize=False, unique=True),
        ),
    ]
