# Generated by Django 3.2.9 on 2021-12-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_alter_product_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('product', 'order')},
        ),
    ]
